### ISSUE TITLE
Can I deploy DVIS model with onnx?

### ISSUE THREAD

**Issue by Wooho-Moon** [zhang-tao-whu/DVIS#1]
Thanks to super awesome work! I'm really impressed on your work :) And I have a quick question.
Can I deploy DVIS model with onnx? if not yet, do you have any plan for that work?

**Comment by zhang-tao-whu** [comment]
Thank you for expressing interest in DVIS. Yes, you can. We welcome improvements and applications based on DVIS.

**Comment by Wooho-Moon** [comment]
Thanks to reply. When I depoly DVIS model with onnx, Do I make a script for that task myself? if not, could I use a tool in this project?
