### ISSUE TITLE
No detections shown

### ISSUE THREAD

**Issue by julkaztwittera** [zhang-tao-whu/DVIS#10]
I tried to use demo on a few videos, but even though there are some instances detected, they aren't shown on the output frames. Lowering the score threshold doesn't help.

**Comment by zhang-tao-whu** [comment]
Thank you for your attention. If you need to adjust the display threshold, you will need to manually modify line 39 of [predictor.py](https://github.com/zhang-tao-whu/DVIS/blob/main/demo_video/predictor.py).

**Comment by zhang-tao-whu** [comment]
Can you provide me with your video so that I can check what caused the failure in detecting any instances?
