### ISSUE TITLE
whether release LSVOS challenge technique report ?

### ISSUE THREAD

**Issue by CarlHuangNuc** [zhang-tao-whu/DVIS#11]
congratulations. "DVIS achieved 1st place in the VIS Track of the 5th LSVOS challenge at ICCV 2023".

I want to ask whether to release the technique report about getting the first award.

Or just the paper code can get it?

**Comment by zhang-tao-whu** [comment]
Thanks for your interest. The champion technology report of LSVOS will be released this week, but the code may be delayed for a while. We have recently made comprehensive enhancements to DVIS, which has resulted in significant performance gains. We will write a paper to introduce DVIS++, and the code will be released together. Please note that the changes mentioned in the technology report do not fully incorporate the modifications of DVIS++.

**Comment by zhang-tao-whu** [comment]
Hi! This is our [technical report](https://arxiv.org/pdf/2308.14392.pdf).
