### ISSUE TITLE
can not use demo file

### ISSUE THREAD

**Issue by beratersari** [zhang-tao-whu/DVIS#15]
![image](https://github.com/zhang-tao-whu/DVIS/assets/56562278/3046ba25-5d86-474a-9580-7032a76e8098)

When I tried to use the demo file. It stops the program with a "keyboard interrupt" error even though I don't press a key

**Comment by zhang-tao-whu** [comment]
Sorry, I've never encountered a similar problem before. Can you provide more detailed information, please?

**Comment by beratersari** [comment]
I just fixed it, I set up the window size to 5. Thanks
