### ISSUE TITLE
🐛[Bugs] I can't reproduce DVIS online results on Youtube-VIS 2019

### ISSUE THREAD

**Issue by clownrat6** [zhang-tao-whu/DVIS#16]
The version of the adopted repo: 39a451467fb8b009d1da6bf9cb704e6ccc5dfb52

The minvis pretraining stage is reproduced perfectly. However, training DVIS online version with minvis pretrain weights just achieve 29.2 mAP. This is my [training log](https://phrarh32db.feishu.cn/file/AiCTbvB83oOp7OxpxC5cnzSRnvc?from=from_copylink). Could you please check this bug?

**Comment by zhang-tao-whu** [comment]
Sorry, currently only one batch can be processed on one GPU. So if you have four GPUs, you need to set `SOLVER.IMS_PER_BATCH to 4`.

**Comment by clownrat6** [comment]
So, the problem is that DVIS can't process multiple batches on a single GPU?

**Comment by zhang-tao-whu** [comment]
Yes, the current version of the code only supports training with one batch per GPU. The performance difference between batch size 4 and batch size 8 is minimal. I will soon modify the code to support multi-batch with a GPU.

**Comment by clownrat6** [comment]
Really thanks for your response. 🙏🙏
