### ISSUE TITLE
can not produce demos

### ISSUE THREAD

**Issue by manli232111** [zhang-tao-whu/DVIS#17]
Hi authors,

Thanks for your great work! I try to produce some demo videos for VIPSeg dataset, but the segmentation results are poor, do I need to change some settings to reproduce the results shown in paper?

Thanks

**Comment by manli232111** [comment]
Following the demo code, I got such demo, I am not sure how to fix it?
<img width="608" alt="1" src="https://github.com/zhang-tao-whu/DVIS/assets/143767516/3cc2caa6-b944-4e76-ac24-9c5b175b9106">

**Comment by zhang-tao-whu** [comment]
Please provide your running command. I guess you used the offline model but loaded the online weights, or used the online model but only loaded the segmenter weights.

**Comment by manli232111** [comment]
Thanks for your reply!

I just git clone DVIS codebase and run the following code, I did not find any errors, could you pls help me check?

 python demo_video/demo_long_video.py --config-file configs/youtubevis_2021/swin/DVIS_Offline_SwinL.yaml --output visual --input datasets/ytvis_2021/valid/JPEGImages/0e4068b53f/ --opt MODEL.WEIGHTS DVIS_offline_ytvis21_swinl.pth

**Comment by zhang-tao-whu** [comment]
Sorry for the delayed response. I downloaded the checkpoint and tested the visual results, and it works very well.
![download](https://github.com/zhang-tao-whu/DVIS/assets/79845037/f8931bc8-3606-49c8-9567-539109108d5f)
![00095](https://github.com/zhang-tao-whu/DVIS/assets/79845037/859051d3-594f-429b-80eb-b08623dd8d3a)

**Comment by zhang-tao-whu** [comment]
This is the complete visual output:
[demo_out-196.zip](https://github.com/zhang-tao-whu/DVIS/files/12913289/demo_out-196.zip)

**Comment by zhang-tao-whu** [comment]
I cannot speculate on what issue you are experiencing. If possible, please provide me with your operating environment, the command you are running, and a complete screenshot of the log.

**Comment by manli232111** [comment]
The issue is due to the environment, I re-install the env and solved the bug. Thanks!
