### ISSUE TITLE
no detection results on demo.py

### ISSUE THREAD

**Issue by manli232111** [zhang-tao-whu/DVIS#18]
Hi,

I am trying to generate some visual results on VSPW dataset, I used VIPSeg's config and ckp, but it detect 0 instances, could you give me any suggestions?

Thanks!

**Comment by zhang-tao-whu** [comment]
There were some bugs in the inference process in VSS mode, but I have fixed them. After testing, it works well now. In VSS mode, the number of instances is not counted, so it will display as 0. 
![download](https://github.com/zhang-tao-whu/DVIS/assets/79845037/cf2da8ed-584f-43a1-80c2-51798dcef2aa)
The results are:
[demo_out-197.zip](https://github.com/zhang-tao-whu/DVIS/files/12913850/demo_out-197.zip)
![00095](https://github.com/zhang-tao-whu/DVIS/assets/79845037/ba29711b-0006-4cf6-96a7-4077a87af2c8)

**Comment by manli232111** [comment]
Thanks much for your help! It works now.
