### ISSUE TITLE
Dataset file missing

### ISSUE THREAD

**Issue by nanle771** [zhang-tao-whu/DVIS#20]
I found that the Annotations file is missing compared to the prepared dataset when downloading the YouTube VIS 2021 dataset. Can you help solve this problem? Download link:https://drive.google.com/drive/folders/12DxR2HWTVjULNwKVMdYAvhOmZ9gBxsX2

**Comment by zhang-tao-whu** [comment]
You can download it from [here](https://codalab.lisn.upsaclay.fr/competitions/7680#participate-get_data).

**Comment by nanle771** [comment]
Yes, I  checked the files and it seems like the annotation files are missing after downloading from [https://codalab.lisn.upsaclay.fr/competitions/7680#participate-get_data](url)

**Comment by nanle771** [comment]
Yes, I checked the files and it seems like the annotation files are missing after downloading from [https://codalab.lisn.upsaclay.fr/competitions/7680#participate-get_data](url)

**Comment by zhang-tao-whu** [comment]
Can you download the train.zip file, extract it, and you will get JPEGImages and instances.json, which are the video and annotation files respectively?

**Comment by nanle771** [comment]
Yes, I can, but I can't find the annotation files,and is instance.json just train.json?

**Comment by zhang-tao-whu** [comment]
Yes, instances.json is indeed the annotation file.

**Comment by nanle771** [comment]
Thank you, I would like to know how to convert instances.json to annotation files in the step of [Preparing Datasets for DVIS](https://github.com/zhang-tao-whu/DVIS/blob/main/datasets/README.md)
