### ISSUE TITLE
About the transformer denoising blocks (TD) 

### ISSUE THREAD

**Issue by nero1342** [zhang-tao-whu/DVIS#22]
Thanks for your great work! 

As I understand, from the frame 2, the Q, K, and V  are consistent on each TD block of the same frame, right? The only change is the ID, which will be updated through L blocks. 

So have you ever tried to experiment with the effectiveness of the number of L?

**Comment by zhang-tao-whu** [comment]
Yes, your understanding is correct. I'm sorry, I haven't explored the impact brought by 'L'. However, I believe achieving a similar performance is possible by using fewer TD blocks, as once the model is well-trained, the initial TD block can also yield good results. Alternatively, substituting 'L' cascaded TD blocks with a single TD block of larger channel capacity might be feasible, as it is theoretically equivalent.
