### ISSUE TITLE
Problem when I evaluate DVIS(online) on OVIS dataset

### ISSUE THREAD

**Issue by xihuachen9804** [zhang-tao-whu/DVIS#24]
Hi! Thank you for your great work!
When I try to evaluate  DVIS(online) on OVIS dataset, I only get "nan" results. Like this:
![Snipaste_2023-11-20_18-19-00](https://github.com/zhang-tao-whu/DVIS/assets/58105525/f2aa28e9-cc08-49e1-a66e-75e8e785ad11)

I can't find the reason. I just change the IMS_PER_BATCH in DVIS_Online_R50.yaml from 8 to 4 in DVIS_Online_R50.yaml. 
Here is my order：python train_net_video.py --num-gpus 4 --config-file configs/ovis/DVIS_Online_R50.yaml --eval-only --resume MODEL.WEIGHTS checkpoints/DVIS_online_ovis_r50.pth。
And my evaluate log is [log.txt](https://github.com/zhang-tao-whu/DVIS/files/13413707/log.txt)

Hope you can help answer.

**Comment by zhang-tao-whu** [comment]
This is normal. OVIS does not provide annotations for the validation set. You need to submit the predicted results.json for evaluation at [here](https://codalab.lisn.upsaclay.fr/competitions/4763#participate-submit_results).
