### ISSUE TITLE
How to Train on New Data

### ISSUE THREAD

**Issue by MKE0108** [zhang-tao-whu/DVIS#28]
Hello, I am interested in training a dataset using your DVIS model. After reading through the GETTING_STARTED.md, my understanding is that I should follow these steps:

1. Finetune the segmenter.
2. Use the weights from the trained segmenter to train DVIS_Online.
3. Use the weights from the trained DVIS_Online to train DVIS_Offline.
<img width="735" alt="image" src="https://github.com/zhang-tao-whu/DVIS/assets/108463217/fa276bd0-a7e6-4ab3-837c-3a784438525e">

Could you please confirm if my understanding is correct?

**Comment by zhang-tao-whu** [comment]
Yes, your understanding is completely correct.
