### ISSUE TITLE
The dataset “ytvis2021” does not have instances.json for validation and test sets. Where does their annotation information come from?

### ISSUE THREAD

**Issue by CoveLSwallow** [zhang-tao-whu/DVIS#29]
Hello, Mr Zhang. The dataset “YoutubeVIS2021” does not have instances.json for validation and test sets. Where does their annotation information come from?

**Comment by zhang-tao-whu** [comment]
Hello, thanks for your attention. You need to submit the predicted results.json to [the official evaluation server](https://codalab.lisn.upsaclay.fr/competitions/7680) to obtain the results.

**Comment by CoveLSwallow** [comment]
Ok! Thanks very much for your promt response and guidance on my question.!




Cove
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-tao-whu/DVIS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月1日(星期五) 中午11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhang-tao-whu/DVIS] The dataset “ytvis2021” does not have instances.json for validation and test sets. Where does their annotation information come from? (Issue #29)





 
Hello, thanks for your attention. You need to submit the predicted results.json to the official evaluation server to obtain the results.
