### ISSUE TITLE
Model wieghts about VSPW dataset

### ISSUE THREAD

**Issue by Wave2689** [zhang-tao-whu/DVIS#3]
Very good idea and project! 
When I test the model on the VSPW dataset, I can't find model weights about it in `Model Zoo`. Where can I find it? Thank you!

**Comment by zhang-tao-whu** [comment]
We will release pre-training weights for the VSPW dataset, likely in mid-July. In the meantime, you can utilize the VSPW configs and VIPSeg pre-training weights to conduct VSS on the VSPW dataset.
For example:
```
python train_net_video.py --config-file configs/VSPW/swin/DVIS_Offline_SwinL_720p.yaml --num-gpus 8 --eval-only MODEL.WEIGHTS DVIS_offline_vipseg_swinl.pth
```

**Comment by Wave2689** [comment]
Thank you very much!

**Comment by zhang-tao-whu** [comment]
DVIS++ has been released, which provides the training weights on VSPW. Please refer to [DVIS++](https://github.com/zhang-tao-whu/DVIS_Plus) for details.
