### ISSUE TITLE
vspw inference results image pixels is all zero

### ISSUE THREAD

**Issue by svitlana1ana** [zhang-tao-whu/DVIS#31]
the command use for inference:
python train_net_video.py \
  --num-gpus 8 \
  --config-file configs/SDG/DVIS_Online_R50_720p.yaml \
  --eval-only MODEL.WEIGHTS output_DVIS_Online_R50_720p_VSPW/model_final.pth

train command:
python train_net_video.py --num-gpus 8 --config-file configs/VSPW/DVIS_Online_R50_720p.yaml \

**Comment by zhang-tao-whu** [comment]
What is SDG? Can you share the config file (configs/SDG/DVIS_Online_R50_720p.yaml ) and the training and testing logs to help me understand your problems?

**Comment by svitlana1ana** [comment]
> What is SDG? Can you share the config file (configs/SDG/DVIS_Online_R50_720p.yaml ) and the training and testing logs to help me understand your problems?

Sorry, I copied the wrong path， the correct config file path is :configs/VSPW/DVIS_Online_R50_720p.yaml. 
I have retrained the model and it can now inference normally,
thank you for your reply!

I would like to know if there has been any progress in your response to issue:#14
