### ISSUE TITLE
About the json file size

### ISSUE THREAD

**Issue by wengkai0** [zhang-tao-whu/DVIS#4]
Hi Siir

Thanks for your excellent job, when I try to evaluate the R-50 DVIS offline on ytvis2019, I found that the generated json file is more than 500+MB, which exceeds the codelab server requirement, is that a normal result? 

Thanks
Kai

**Comment by zhang-tao-whu** [comment]
Hi !
It doesn't appear to be normal. The results.json file obtained from the ytvis19 dataset is typically around 80MB in size, and it should be smaller when compressed into a zip file. Could you please provide me with more information to assist in identifying the issue?

**Comment by wengkai0** [comment]
Hi, thanks for your information. I think it is because of the environment. After re-installing the environment. I got the reasonable results.

I also want to ask you another question related to the training with num_worker > 0, I found that during training is shut down at around 30000 iterations because of the file read error ( unable to open shared memory object </torch_1655_4056744771> in read-write mode)

I trained with 2 GPUs.

Thanks!

**Comment by zhang-tao-whu** [comment]
I'm sorry, I haven't come across such a situation. I have been using PyTorch 1.9.0 (cuda 10.2 or cuda 11.3) without any issues. I believe the problem you're experiencing might be related to the version of PyTorch you're using. You can try switching to a different version.

**Comment by JinYoon002** [comment]
Hi, @zhang-tao-whu 

I also installed the environment following your instruction using PyTorch 1.9.0 with cuda11.1,

I met this issue at around 30000 iterations: UserWarning: resource_tracker: There appear to be 28 leaked semaphore objects to clean up at shut down and the work is shut down automatically.

Do you have any suggestions about this issue?

**Comment by zhang-tao-whu** [comment]
Please provide more detailed logs and information.
