### ISSUE TITLE
VSS bug 

### ISSUE THREAD

**Issue by wengkai0** [zhang-tao-whu/DVIS#5]
Hi, authors,

Thanks for your great work!
I met a few problems when running VSS code, could you pls give any suggestions?

1. How do I train DVIS on VSS? (following which config file?) 
2. and What is the difference between 480p and 720p dataset?

I follow the code python train_net_video.py --num-gpus 4 --config-file configs/VSPW/MinVIS_R50_480p.yaml 

The traceback error is : sem_seg_gt[sem_seg_gt == 0] = 255
ValueError: assignment destination is read-only

Thanks!

**Comment by zhang-tao-whu** [comment]
Sorry, I will check and fix this bug as soon as possible.

**Comment by wengkai0** [comment]
Thanks! 

I also found that the inference code for VPS and VSS does not work. Since the current code does not specify that it is one of the tasks in VSS or VPS. Could you please have a check?

**Comment by zhang-tao-whu** [comment]
Could you provide your config file? `cfg.MODEL.MASK_FORMER.TEST.TASK` specifies the specified inference task ('vis', 'vss'or 'vps') for the network. Please refer to line 22 of [config](https://github.com/zhang-tao-whu/DVIS/blob/main/configs/VIPSeg/Base-VIPSeg-VideoInstanceSegmentation.yaml).

**Comment by wengkai0** [comment]
Hi Zhangtao,

Thanks for your information, I will have a try and give feedback to you.

And could I put more than one samples in one GPU to train DVIS?

Thanks

**Comment by zhang-tao-whu** [comment]
I'm sorry, currently we only support one GPU per batch of video data. However, there's a possibility that in the future, we may support multiple batches of video for a single GPU.

**Comment by wengkai0** [comment]
Thanks for your prompt reply, It helps a lot!
