### ISSUE TITLE
A problem to submit result

### ISSUE THREAD

**Issue by yuyuan2** [zhang-tao-whu/DVIS#7]
Hi, I try to get the inference result by submitting esult_submission.zip on the server for video panoptic segmentation swin-L, but failed. The errors are shown below, could you please check?

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmp4vzAlN/run/program/score.py", line 815, in 
    pred_js = pred_j[video_id]
KeyError: '1001_5z_ijQjUf_0'

**Comment by zhang-tao-whu** [comment]
Perhaps it's possible that the test.json file of the VIPSeg dataset may not be correct, as the image file names are not organized in order. You can try regenerating it using the [gen_VIPSeg_test_json.py](https://github.com/zhang-tao-whu/DVIS/blob/main/utils/gen_VIPSeg_test_json.py).

**Comment by yuyuan2** [comment]
Hi, Thanks for your answer,

I have another question about VSPW: is there any difference between 480P and 720P? When training DVIS, should I train it on 480P first, and then 720P? 

Thanks!

**Comment by zhang-tao-whu** [comment]
No. You just need to choose one scale for training and testing. If you have enough GPU memory, you can use 720p for training and testing, which will yield higher performance. If you have limited GPU memory, you can choose 480p or smaller sizes.
