### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by SoftSisterRui** [zhang-tao-whu/DVIS#8]
Hello, the dataset I use is youtubevis, and my data structure is as follows:
ytvis_2021/
   train.json
   valid.json
   train/
     Annotations/
     JPEGImages/
   valid/
     Annotations/
     JPEGImages/
And I put them under the datasets file.

But when I train with this command: 
python train_net_video.py --num-gpus 2 --config-file ./configs/youtubevis_2021/swin/DVIS_Offline_SwinL.yaml --resume MODEL.WEIGHTS ./pretrain/DVIS_offline_ytvis21_swinl.pth
The following error occurred:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/annotations/coco2ytvis2021_train.json'
Do I need a json file in coco format for training?

**Comment by zhang-tao-whu** [comment]
Please prepare the coco dataset according or remove the coco dataset from the config file.
